# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoAppV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoAppV2
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'TodoAppV2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
